### ISSUE TITLE
调用  remove问题

### ISSUE THREAD

**Issue by dcbase** [chiporyu/maptalks.routeplayer#2]
![image](https://user-images.githubusercontent.com/21169222/78853626-ea4bd780-7a51-11ea-9ec0-2bfe0961acaa.png)
 drawAnimaPath(data){
            console.log(this.player)
            if(this.player){
                this.player.remove()
            }
            let map = this.mapInstance
            let path = []
            data.map((item) => {
                path.push([item.longitude,item.latitude,item.time])
            })
            let routes = [{
                path: path,
                lineSymbol: {
                    lineWidth: 2,
                    lineColor: '#30D385',
                    markerFile:  require(`images/maptalks/pollution/${this.type}.png`),
                    markerPlacement: 'vertex-last', //vertex, point, vertex-first, vertex-last, center
                    markerVerticalAlignment: 'middle',
                    markerWidth: 24,
                    markerHeight: 24
                }
            }]
            this.player = new VectorRoutePlayer(routes, map);
            this.player.setSpeed(100)
            this.player.play()
        },

为啥remove方法没有移除这个图层呢？？？？

**Comment by chiporyu** [comment]
remove方法存在bug，在0.1.3版本已经修复。请更新到新的版本
